# Generated by Django 4.2.3 on 2023-08-06 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telp', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.eventorganizer')),
            ],
        ),
    ]
