# Generated by Django 4.2.3 on 2023-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
